#pragma once

enum class TokenType {
    // Meta
    TOKEN_EOF,
    TOKEN_ERROR,

    // Literals
    TOKEN_IDENTIFIER,
    TOKEN_UNQUOTED_LITERAL,
    TOKEN_STRING_DOUBLE,
    TOKEN_STRING_SINGLE,
    TOKEN_NUMBER,

    // Punctuation & Symbols
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACK,
    TOKEN_RBRACK,
    TOKEN_SEMICOLON,
    TOKEN_COLON,
    TOKEN_EQUAL,
    TOKEN_COMMA,
    TOKEN_DOT,
    TOKEN_HASH,
    TOKEN_AT,
    TOKEN_AT_IDENTIFIER,
    TOKEN_AMPERSAND,
    TOKEN_QUESTION,
    TOKEN_DOLLAR,

    // Operators
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_STAR,
    TOKEN_SLASH,
    TOKEN_PERCENT,
    TOKEN_STAR_STAR,
    TOKEN_GT,
    TOKEN_LT,
    TOKEN_LOGICAL_AND,
    TOKEN_LOGICAL_OR,

    // Comments
    TOKEN_COMMENT_SINGLE,
    TOKEN_COMMENT_MULTI,
    TOKEN_COMMENT_GENERATOR,

    // Keywords
    TOKEN_KEYWORD_TEXT,
    TOKEN_KEYWORD_STYLE,
    TOKEN_KEYWORD_SCRIPT,
    TOKEN_KEYWORD_TEMPLATE,
    TOKEN_KEYWORD_CUSTOM,
    TOKEN_KEYWORD_ORIGIN,
    TOKEN_KEYWORD_IMPORT,
    TOKEN_KEYWORD_NAMESPACE,
    TOKEN_KEYWORD_CONFIGURATION, // Added
    TOKEN_KEYWORD_FROM,
    TOKEN_KEYWORD_AS,
    TOKEN_KEYWORD_USE,
    TOKEN_KEYWORD_EXCEPT,
    TOKEN_KEYWORD_DELETE,
    TOKEN_KEYWORD_INSERT,
    TOKEN_KEYWORD_INHERIT,
};
